# @package _global_
defaults:
  - _self_
alpha: 0.5
beta: 0.5
num_centers: 1
model:
  _target_: models.arch.ORDL.ORDL
  backbone: ${backbone.backbone}
  num_classes: ${eval:"len(${dataset.known_class})"}
  feat_dim: ${backbone.feat_dim}
  num_centers: ${num_centers}

trainer:
  _target_: trainers.ORDL.OrdlTrainer

criterion:
  _target_: models.loss.ORDL.OrdlLoss
  # alpha: ${alpha}
  # beta: ${beta}
  # num_classes: ${eval:"len(${dataset.known_class})"}
  # feat_dim: 512