defaults:
  - _self_
  - /dataset: cifar10
  - /backbone: vgg16
  - /models: ORDL
  - /optim: adam
  - /scheduler: step

dataset_name: ${hydra:runtime.choices.dataset}

train_bs: 64
test_bs: 64
epochs: 100