defaults:
  - _self_
  # - /dataset: cifar10
  - /dataset: ISIC
  # - /dataset: Dermnet_Skin_Disease
  - /backbone: resnet18_224
  # - /backbone: resnet18_32
  # - /backbone: classifier32
  - /models: ORDL
  - /optim: sgd
  - /scheduler: multistep

dataset_name: ${hydra:runtime.choices.dataset}

open_test: True
train_bs: 64
test_bs: 64
epochs: 100
neval: 10
indicator: AUROC

tag: ""
seed: 3096
work_dir: ${hydra:runtime.cwd}
# data_dir: ${work_dir}
hydra:
  run:
    dir: ${work_dir}/logs/${hydra:runtime.choices.dataset}/${hydra:runtime.choices.models}_${epochs}/${tag}${seed}_${now:%y%m%d_%H%M%S_%f}
  job:
    chdir: False

logdir: ${hydra:run.dir}